### model
model_name_or_path: models/llama3.1-8b-pro

### method
stage: sft
do_train: true
finetuning_type: freeze
freeze_trainable_layers: 4
freeze_trainable_modules: all
use_llama_pro: true
use_liger_kernel: true
flash_attn: fa2

### dataset
dataset: longhorn_sample
template: llama3
cutoff_len: 40000
max_samples: 1000000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama31-8b-pro/4_blocks_longhorn
logging_steps: 10
save_steps: 1500000000000000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 0.00002
max_grad_norm: 3.0
num_train_epochs: 80.0
lr_scheduler_type: constant
# warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500