### model
model_name_or_path: models/Phi-3.5-mini-instruct-pro-4

### method
stage: sft
do_train: true
finetuning_type: freeze
freeze_trainable_layers: 4
freeze_trainable_modules: all
use_llama_pro: true
use_liger_kernel: true
flash_attn: fa2

### dataset
dataset: function_calling_post_filtering_v4, function_calling_post_filtering_v4, function_calling_post_filtering_v4, function_calling_post_filtering_v4, function_calling_post_filtering_v4, mmlu_pro_training, WildChat_116k_functions
template: phi-rubra
cutoff_len: 400000
max_samples: 1000000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Phi-3.5-mini-instruct-pro-4/function_calling_post_filtering_v4
logging_steps: 10
save_steps: 30000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 3
learning_rate: 0.00002
max_grad_norm: 3.0
num_train_epochs: 2
lr_scheduler_type: cosine_with_restarts
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500